# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='current_travelers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='curr_travs', to='first_app.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='destfrom',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='trip',
            name='destto',
            field=models.CharField(default='', max_length=70),
        ),
    ]
