# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170425_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_travelers',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curr_travs', to='first_app.User'),
        ),
    ]
